export const UI = {
  navNewAnalysis: 'Yeni Analiz',
  navHistory: 'Koku Geçmişi',
  navCompare: 'Karşılaştır',
  navWardrobe: 'Koku Dolabım',
  navWearRoutine: 'Koku Rutinim',
  navLayeringLab: 'Katmanlama Lab',
  navNoteFinder: 'Nota Avcısı',
  navBarcode: 'Barkod Tara',
  navFeed: 'Koku Akışı',
  navDailyLimit: 'Günlük analiz',
  navUpgrade: "Pro'ya Geç",

  pageHome: 'Koku Dedektifi',
  pageWardrobe: 'Koku Dolabım',
  pageHistory: 'Koku Geçmişi',
  pageWear: 'Koku Rutinim',
  pagePackages: 'Paketler',
  pagePrivacy: 'Gizlilik Politikası',
  pageTerms: 'Kullanım Koşulları',
  pageRefund: 'İade Politikası',

  heroEyebrow: 'AI parfüm analizi',
  heroTitle: 'Bir koku anlat,',
  heroTitleItalic: 'sırrını çözelim.',
  heroSubtitle: 'Fotoğraf, parfüm adı veya koku notalarıyla başla.',

  tabPhoto: 'Fotoğraf',
  tabText: 'Metin',
  tabNotes: 'Nota Listesi',
  photoPlaceholder: 'Fotoğraf çek veya seç',
  photoHelper: 'Şişe, kutu veya ortam fotoğrafı yükle.',
  textPlaceholder: "Dior Sauvage, Creed Aventus ya da 'odunsu ama çok ağır değil' gibi yaz...",
  notesPlaceholder: 'Notaları virgülle ayırarak gir',
  notesHelper: 'Örnek: bergamot, sedir, vanilya, paçuli',
  analyzeBtn: 'Kokuyu Analiz Et',
  analyzing: 'Yapay zeka analiz ediyor...',
  analysisSteps: 'Profil çözümleme, nota piramidi ve molekül katmanı oluşturuluyor.',

  chipSectionLabel: 'Popüler aramalar',
  chipSauvage: 'Dior Sauvage',
  chipAventus: 'Creed Aventus',
  chipFireplace: 'By the Fireplace',
  chipOudRose: 'Oud + Gül',
  chipCleanSea: 'Temiz Deniz',
  chipVanillaAmber: 'Vanilya + Amber',

  actionAddWardrobe: 'Dolaba Ekle',
  actionCompare: 'Karşılaştır',
  actionLayer: 'Katmanla',
  actionSave: 'Kaydet',
  actionNewAnalysis: 'Yeni Analiz Yap',
  actionClearHistory: 'Geçmişi Temizle',

  wardrobeAll: 'Tümü',
  wardrobeOwned: 'Sahibim',
  wardrobeWishlist: 'İstek Listesi',
  wardrobeTried: 'Denedim',
  wardrobeBuyAgain: 'Tekrar Alırım',
  wardrobeSkip: 'Geçti',

  emptyWardrobeTitle: 'Dolabın henüz boş',
  emptyWardrobeBody: 'Analiz yaptıkça parfümlerini buraya ekleyebilirsin.',
  emptyWardrobeBtn: 'İlk Analizi Yap',
  emptyHistoryTitle: 'Henüz geçmiş yok',
  emptyHistoryBody: 'İlk analizini yaptığında sonuçların burada birikir.',
  emptyCommunityTitle: 'İlk yorumu sen bırak',
  emptyCommunityBody: 'Bu koku için henüz topluluk sinyali oluşmadı.',
  emptyLayeringTitle: 'Katmanlama için iki parfüm gerek',
  emptyLayeringBody: 'Önce dolabına en az iki parfüm ekle, sonra en iyi kombinasyonu birlikte çıkaralım.',
  emptyLayeringBtn: 'Dolaba Git',
  wearEmptyTitle: 'Henüz kayıt yok',
  wearEmptyBody: 'Analiz geçmişin arttıkça kişisel koku rutinin burada şekillenecek.',

  packagesHero: 'Koku keşfini ücretsiz başlat, Pro ile derinleştir.',
  packagesFreeTitle: 'Ücretsiz',
  packagesFreePrice: '0 TL',
  packagesFreeTag: 'Başlangıç seviyesi',
  packagesFreeFeatures: ['Günlük 3 analiz', 'Koku dolabı', 'Karşılaştırma'],
  packagesFreeBtn: 'Ücretsiz Başla',
  packagesProTitle: 'Pro',
  packagesProTag: 'Önerilen',
  packagesProFeatures: [
    'Sınırsız analiz',
    'Katmanlama Lab',
    'Barkod Tarayıcı',
    'Cihazlar arası senkronizasyon',
    'Öncelikli AI',
  ],
  packagesProBtn: "Pro'ya Geç",

  wearSummaryTitle: 'Genel Özet',
  wearAnalysisCount: 'Toplam analiz kaydı',
  wearFamilyDist: 'Aile Dağılımı',
  wearNoDataNote: 'Analiz geçmişin arttıkça bu alan kişisel koku ritmine dönüşür.',

  detectedScent: 'Tespit Edilen Koku',
  scentDescription: 'Koku Açıklaması',
  pyramid: 'Koku Piramidi',
  topNote: 'Üst',
  heartNote: 'Kalp',
  baseNote: 'Alt',
  wheel: 'Koku Çarkı',
  keyMolecules: 'Anahtar Moleküller',
  similarScents: 'Benzer Profil Önerileri',
  communityPulse: 'Topluluk Nabzı',
  suitability: 'Sana Yakışır mı?',

  proLabel: 'Pro',
  loginBtn: 'Giriş Yap',
  registerBtn: 'Kayıt Ol',
  logoutBtn: 'Çıkış Yap',
  saveProfile: 'Profili Kaydet',
  copyright: '© 2026 Koku Dedektifi',

  newAnalysis: 'Yeni Analiz',
  history: 'Koku Geçmişi',
  compare: 'Karşılaştır',
  wardrobe: 'Koku Dolabım',
  wearTracker: 'Koku Rutinim',
  layeringLab: 'Katmanlama Lab',
  noteFinder: 'Nota Avcısı',
  barcodeScanner: 'Barkod Tara',
  feed: 'Koku Akışı',
  photoTab: 'Fotoğraf',
  textTab: 'Metin',
  notesTab: 'Nota Listesi',
  addToWardrobe: 'Dolaba Ekle',
  compareBtn: 'Karşılaştır',
  layerBtn: 'Katmanla',
  saveResult: 'Kaydet',
  newAnalysisBtn: 'Yeni Analiz Yap',
  clearHistory: 'Geçmişi Temizle',
  login: 'Giriş Yap',
  register: 'Kayıt Ol',
  logout: 'Çıkış Yap',
  city: 'Şehir',
  budgetRange: 'Bütçe Aralığı',
  upgradeToPro: "Pro'ya Geç",
  quickStart: 'Hızlı Başlangıç',
  quickStartSub: 'İki dakikada profiline uygun başlangıç akışını oluşturalım.',
  skip: 'Geç',
  skipForNow: 'Şimdilik Geç',
  scentGoal: 'Koku Amacın',
  budgetBand: 'Bütçe Bandın',
  favoriteFamily: 'Favori Aileler',
  saveAndContinue: 'Kaydet ve Devam',
  prepareFirstAnalysis: 'İlk Analizi Hazırla',
  emptyWardrobe: 'Dolabın henüz boş',
  emptyWardrobeSub: 'Analiz yaptıkça parfümlerini buraya ekleyebilirsin.',
  emptyCommunity: 'Henüz topluluk sinyali yok',
  emptyCommunitySub: 'Bu koku için ilk geri bildirimi sen bırak.',
  wearTrackerSub: 'Analiz geçmişin arttıkça kişisel rutin özetin burada görünecek.',
  dailyUsage: 'Günlük analiz',
  barcodeManual: 'Barkod (manuel)',
  barcodeSearch: 'Barkodu Ara',
  includeNotes: 'Dahil notalar',
  excludeNotes: 'Hariç notalar',
  maxSweetness: 'Maks. tatlılık (0-100)',
  targetSweetness: 'Hedef tatlılık (0-100)',
  getResults: 'Sonuçları Getir',
  leftScent: 'Sol parfüm',
  rightScent: 'Sağ parfüm',
  analyzeLayering: 'Katmanlamayı Analiz Et',
} as const;

export type UIKey = keyof typeof UI;
