-- Koku Dedektifi - Supabase schema (wardrobe + advisor RAG)
-- Run in Supabase SQL editor.

create extension if not exists vector;

-- Auth users table (cross-device identity source for web + mobile wrapper)
create table if not exists public.app_users (
  id text primary key,
  email text not null unique,
  name text not null default '',
  salt text not null default '',
  password_hash text not null default '',
  profile_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create index if not exists app_users_email_idx
  on public.app_users (email);

create table if not exists public.scent_wardrobe (
  user_id text primary key,
  shelf_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists scent_wardrobe_updated_at_idx
  on public.scent_wardrobe (updated_at desc);

create table if not exists public.community_feed (
  user_id text primary key,
  feed_json jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists community_feed_updated_at_idx
  on public.community_feed (updated_at desc);

-- Optional FK (safe when ids are managed by app):
do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where constraint_name = 'scent_wardrobe_user_fk'
      and table_schema = 'public'
      and table_name = 'scent_wardrobe'
  ) then
    alter table public.scent_wardrobe
      add constraint scent_wardrobe_user_fk
      foreign key (user_id) references public.app_users(id)
      on delete cascade;
  end if;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where constraint_name = 'community_feed_user_fk'
      and table_schema = 'public'
      and table_name = 'community_feed'
  ) then
    alter table public.community_feed
      add constraint community_feed_user_fk
      foreign key (user_id) references public.app_users(id)
      on delete cascade;
  end if;
exception
  when duplicate_object then null;
end $$;

-- RLS hardening:
-- Service role key (backend) bypasses RLS, but anon/authenticated traffic is blocked by default.
alter table public.app_users enable row level security;
alter table public.scent_wardrobe enable row level security;
alter table public.community_feed enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'app_users'
      and policyname = 'app_users_owner_read'
  ) then
    create policy app_users_owner_read on public.app_users
      for select
      to authenticated
      using (id = auth.uid()::text);
  end if;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'app_users'
      and policyname = 'app_users_owner_update'
  ) then
    create policy app_users_owner_update on public.app_users
      for update
      to authenticated
      using (id = auth.uid()::text)
      with check (id = auth.uid()::text);
  end if;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'scent_wardrobe'
      and policyname = 'scent_wardrobe_owner_all'
  ) then
    create policy scent_wardrobe_owner_all on public.scent_wardrobe
      for all
      to authenticated
      using (user_id = auth.uid()::text)
      with check (user_id = auth.uid()::text);
  end if;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'community_feed'
      and policyname = 'community_feed_owner_all'
  ) then
    create policy community_feed_owner_all on public.community_feed
      for all
      to authenticated
      using (user_id = auth.uid()::text)
      with check (user_id = auth.uid()::text);
  end if;
exception
  when duplicate_object then null;
end $$;

-- Optional: advisor RAG document store
create table if not exists public.perfume_docs (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  doc_type text not null default 'perfume',
  title text not null,
  content text not null default '',
  family text not null default '',
  occasion text not null default '',
  url text not null default '',
  embedding vector(768) not null,
  created_at timestamptz not null default now()
);

alter table public.perfume_docs
  add column if not exists external_id text;
alter table public.perfume_docs
  add column if not exists doc_type text not null default 'perfume';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'perfume_docs_external_id_key'
  ) then
    alter table public.perfume_docs
      add constraint perfume_docs_external_id_key unique (external_id);
  end if;
exception
  when duplicate_object then null;
end $$;

create index if not exists perfume_docs_embedding_idx
  on public.perfume_docs using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create index if not exists perfume_docs_doc_type_idx
  on public.perfume_docs (doc_type);

create or replace function public.match_perfume_docs(
  query_embedding vector(768),
  match_count int default 6
)
returns table (
  id bigint,
  doc_type text,
  title text,
  content text,
  family text,
  occasion text,
  url text,
  score float
)
language sql
stable
as $$
  select
    d.id,
    d.doc_type,
    d.title,
    d.content,
    d.family,
    d.occasion,
    d.url,
    1 - (d.embedding <=> query_embedding) as score
  from public.perfume_docs d
  order by d.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;
